import React, { useState } from "react";
import { createRoot } from "react-dom/client";
import { QueryClient, QueryClientProvider, useQuery } from "@tanstack/react-query";
import { BrowserRouter, Link, Route, Routes } from "react-router-dom";
import "./style.css";

type Session = { id:string; source:string; status:string; mode:string; title:string; created_at:string; finished_at?:string };
const queryClient = new QueryClient();
const getJson = async (url:string) => { const r = await fetch(url, {credentials:"same-origin"}); if (r.status === 401) throw new Error("unauthorized"); if (!r.ok) throw new Error(await r.text()); return r.json(); };

function Shell({children}:{children:React.ReactNode}) {
  return <div className="shell"><aside><h1>Koda</h1><p className="muted">Agent control plane</p><nav><Link to="/dashboard">Vue d’ensemble</Link><Link to="/sessions">Sessions</Link><Link to="/projects">Projets & politiques</Link><Link to="/skills">Skills & MCP</Link><Link to="/integrations">Intégrations</Link><Link to="/audit">Audit</Link></nav></aside><main>{children}</main></div>;
}
function Dashboard() { const sessions = useQuery<Session[]>({queryKey:["sessions"],queryFn:()=>getJson("/api/v1/sessions")}); const summary = useQuery<any>({queryKey:["summary"],queryFn:()=>getJson("/api/v1/dashboard/summary")}); return <Shell><header><div><span className="eyebrow">OPERATIONS</span><h2>Vue d’ensemble</h2></div><a className="button secondary" href="/logout">Déconnexion</a></header><section className="cards"><article><span>Actives</span><strong>{summary.data?.active ?? "—"}</strong></article><article><span>Sept derniers jours</span><strong>{summary.data?.week ?? "—"}</strong></article><article><span>En attente</span><strong>{summary.data?.awaiting_approval ?? "—"}</strong></article><article><span>Bloquées</span><strong>{summary.data?.blocked ?? "—"}</strong></article></section><section className="panel"><div className="panel-title"><h3>Sessions récentes</h3><Link to="/sessions">Voir tout</Link></div>{sessions.isLoading ? <p>Chargement…</p> : <table><thead><tr><th>Source</th><th>Titre</th><th>Statut</th><th>Créée</th></tr></thead><tbody>{(sessions.data ?? []).slice(0,10).map(s=><tr key={s.id}><td>{s.source}</td><td><Link to={`/sessions/${s.id}`}>{s.title}</Link></td><td><span className={`badge ${s.status}`}>{s.status}</span></td><td>{new Date(s.created_at).toLocaleString()}</td></tr>)}</tbody></table>}</section></Shell>; }
function Sessions() { const q = useQuery<Session[]>({queryKey:["sessions"],queryFn:()=>getJson("/api/v1/sessions")}); return <Shell><header><div><span className="eyebrow">CONTROL</span><h2>Sessions</h2></div></header><section className="panel"><table><thead><tr><th>Source</th><th>Titre</th><th>Mode</th><th>Statut</th><th>Date</th></tr></thead><tbody>{(q.data ?? []).map(s=><tr key={s.id}><td>{s.source}</td><td><Link to={`/sessions/${s.id}`}>{s.title}</Link></td><td>{s.mode}</td><td><span className={`badge ${s.status}`}>{s.status}</span></td><td>{new Date(s.created_at).toLocaleString()}</td></tr>)}</tbody></table></section></Shell>; }
function Detail({id}:{id:string}) { const q = useQuery<any>({queryKey:["session",id],queryFn:()=>getJson(`/api/v1/sessions/${id}`)}); return <Shell><header><div><span className="eyebrow">SESSION</span><h2>{q.data?.title ?? "Session"}</h2></div><Link className="button secondary" to="/sessions">Retour</Link></header><section className="panel"><p><b>Statut :</b> {q.data?.status}</p><p><b>Workflow :</b> {q.data?.workflow_type ?? q.data?.mode}</p><p><b>Preuve :</b> <code>{q.data?.evidence_hash ?? "en cours"}</code></p><h3>Événements</h3><pre>{JSON.stringify(q.data?.events ?? [], null, 2)}</pre>{q.data?.approval_state === "pending" && <div className="actions"><button className="button" onClick={()=>fetch(`/api/v1/sessions/${id}/approval`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({decision:"approve",evidence_hash:q.data.evidence_hash})}).then(()=>q.refetch())}>Approuver</button><button className="button danger">Rejeter</button></div>}</section></Shell>; }
function ConfigPage({title,endpoint,kind}:{title:string;endpoint:string;kind:"project"|"integration"|"mcp"|"skills"|"audit"}) {
  const q=useQuery<any[]>({queryKey:[endpoint],queryFn:()=>getJson(endpoint)}); const [name,setName]=useState(""); const [path,setPath]=useState(""); const [url,setUrl]=useState("");
  const submit=async(e:React.FormEvent)=>{e.preventDefault();let body:any={name};if(kind==="project")body={name,gitlab_project_id:path,gitlab_project_path:path,policy:{mode:"read_only"}};if(kind==="integration")body={name,kind:"gitlab",base_url:url,auth_mode:"token"};if(kind==="mcp")body={name,slug:name.toLowerCase().replace(/[^a-z0-9]+/g,"-"),endpoint:url,allowed_hosts:[new URL(url).hostname]};await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify(body)});setName("");setPath("");setUrl("");q.refetch();};
  return <Shell><header><div><span className="eyebrow">CONFIGURATION</span><h2>{title}</h2></div></header><section className="panel">{kind!=="audit"&&<form className="inline-form" onSubmit={submit}><input placeholder="Nom" value={name} onChange={e=>setName(e.target.value)} required />{kind==="project"&&<input placeholder="ID ou chemin GitLab" value={path} onChange={e=>setPath(e.target.value)} required />}{(kind==="integration"||kind==="mcp")&&<input placeholder="URL HTTPS" value={url} onChange={e=>setUrl(e.target.value)} required />}<button className="button">Ajouter</button></form>}<table><thead><tr><th>Nom</th><th>Détails</th><th>Statut</th></tr></thead><tbody>{(q.data??[]).map((x:any)=><tr key={x.id??x.slug}><td>{x.name??x.slug??x.action}</td><td><code>{x.base_url??x.endpoint??x.gitlab_project_path??x.metadata??"—"}</code></td><td>{x.enabled===false?"désactivé":"actif"}</td></tr>)}</tbody></table></section></Shell>;
}
function App() { return <Routes><Route path="/" element={<Dashboard/>}/><Route path="/dashboard" element={<Dashboard/>}/><Route path="/sessions" element={<Sessions/>}/><Route path="/sessions/:id" element={<DetailRoute/>}/><Route path="/projects" element={<ConfigPage title="Projets & politiques" endpoint="/api/v1/projects" kind="project"/>}/><Route path="/skills" element={<ConfigPage title="Skills & MCP" endpoint="/api/v1/mcp-servers" kind="mcp"/>}/><Route path="/integrations" element={<ConfigPage title="Intégrations" endpoint="/api/v1/integrations" kind="integration"/>}/><Route path="/audit" element={<ConfigPage title="Journal d’audit" endpoint="/api/v1/audit" kind="audit"/>}/></Routes>; }
function DetailRoute() { const id = location.pathname.split("/").pop()!; return <Detail id={id}/>; }
createRoot(document.getElementById("root")!).render(<React.StrictMode><QueryClientProvider client={queryClient}><BrowserRouter><App/></BrowserRouter></QueryClientProvider></React.StrictMode>);
